
server:
  port: ${SERVER_PORT:8081}

spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:anil.ravula.gemini@gmail.com}
    password: ${SMTP_PASSWORD:cmmiznjxoutqczzb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
